### ISSUE TITLE
Unhandled Exception

### ISSUE THREAD

**Issue by tgonzalez89** [shalzuth/D2RModding#1]
I'm getting the following error:

Unhandled Exception: System.ComponentModel.Win32Exception: Only part of a ReadProcessMemory or WriteProcessMemory request was completed
   at System.Diagnostics.NtProcessManager.GetModuleInfos(Int32 processId, Boolean firstModuleOnly)
   at System.Diagnostics.NtProcessManager.GetFirstModuleInfo(Int32 processId)
   at System.Diagnostics.Process.get_MainModule()
   at D2RModding.Program.Main(String[] args)

**Comment by zqx1337** [comment]
I had the same error.

Download this project: 
https://github.com/barncastle/Battle.Net-Installer/releases/tag/v1.3 

Then create a .bat with this: 

BNetInstaller.exe --prod osib --lang enus --dir "C:\D2R"

**Comment by shalzuth** [comment]
@tgonzalez89 Can you try running again or running as admin? Is your pc fast or slow?

**Comment by tgonzalez89** [comment]
Running as admin didn't make a difference.
PC is neither fast not slow, it's a i7-5930K@4.2GHz, fast 6 years ago, meh today.

**Comment by ssassassassa** [comment]
getting error while installing BnetInstaller

C:\Users\PC>cd C:\Users\PC\Desktop\D2R

C:\Users\PC\Desktop\D2R>BNetInstaller.exe --prod osib --lang enus --dir "C:\D2R"

Authenticating
Queuing Install
Starting Install

Unhandled exception. System.Exception: Agent Error: 2421
 ---> System.Exception: {
  "error": 2421
}
   --- End of inner exception stack trace ---
   at BNetInstaller.Endpoints.BaseEndpoint.Deserialize(HttpResponseMessage respo
nse)
   at BNetInstaller.Endpoints.Update.UpdateEndpoint.Post()
   at BNetInstaller.Program.InstallProduct(Options options, AgentApp app)
   at BNetInstaller.Program.Run(Options options)
   at BNetInstaller.Program.Main(String[] args)
   at BNetInstaller.Program.<Main>(String[] args)

**Comment by zqx1337** [comment]
You need to set the path of your d2r Installation in the command. I needed to download the files seperatly and then execute the command. 
I could then get into the game but it crashed after some seconds. 
I use this now and works at least in hosted games 
https://github.com/ferib/D2R-Offline

**Comment by ssassassassa** [comment]
got you
but still the same error

C:\Users\PC\Desktop\D2R>BNetInstaller.exe --prod osib --lang enus --dir C:\Users
\PC\Desktop\D2R
Authenticating
Queuing Install
Starting Install

Unhandled exception. System.Exception: Agent Error: 2421
 ---> System.Exception: {
  "error": 2421
}
   --- End of inner exception stack trace ---
   at BNetInstaller.Endpoints.BaseEndpoint.Deserialize(HttpResponseMessage respo
nse)
   at BNetInstaller.Endpoints.Update.UpdateEndpoint.Post()
   at BNetInstaller.Program.InstallProduct(Options options, AgentApp app)
   at BNetInstaller.Program.Run(Options options)
   at BNetInstaller.Program.Main(String[] args)
   at BNetInstaller.Program.<Main>(String[] args)

**Comment by wolfcon** [comment]
- Restart your computer
- Don't use vpn or other network accelerator.
Then retry it
Did it and work for me

**Comment by talaue** [comment]
> I'm getting the following error:
> 
> Unhandled Exception: System.ComponentModel.Win32Exception: Only part of a ReadProcessMemory or WriteProcessMemory request was completed
> at System.Diagnostics.NtProcessManager.GetModuleInfos(Int32 processId, Boolean firstModuleOnly)
> at System.Diagnostics.NtProcessManager.GetFirstModuleInfo(Int32 processId)
> at System.Diagnostics.Process.get_MainModule()
> at D2RModding.Program.Main(String[] args)

I'm getting the same error when running D2RModding in the same directory as Game.exe

**Comment by shalzuth** [comment]
I pushed a change that should help https://github.com/shalzuth/D2RModding/releases/download/1.0.1/D2RModding.exe

**Comment by talaue** [comment]
The game wont open at all now.  The cmd window opens, nothing happens, and then it closes. I tried opening it without starting the Battle.net app, and got a prompt saying that it required Battle.net to be running. So I started Battle.net and now nothings happening. I ran the D2RModding.exe as admin as well, still doesn't work.

**Comment by talaue** [comment]
Ok, so I did a few things and finally got it working. First, I updated my NVIDIA drivers. I don't think that's what fixed the issue, but it might have been a part of the issue anyway.

What seems to have finally fixed the issue was opening the b.net client, seeing that it recognized that D2R Tech Alpha was installed, clicking on the gear icon at the bottom of the screen next to "Update" and selecting "Scan and Repair" and then running D2RModding.exe after that. Game opened up for me.

**Comment by n0vares** [comment]
Although I didn't have this problem, and it worked just fine for me... two people I've tried to help follow the same process get the error below with BNetInstaller.exe:

C:\Users\PC\Desktop\D2R>BNetInstaller.exe --prod osib --lang enus --dir C:\Users
\PC\Desktop\D2R
Authenticating
Queuing Install
Starting Install

Unhandled exception. System.Exception: Agent Error: 2421
---> System.Exception: {
"error": 2421
}
--- End of inner exception stack trace ---
at BNetInstaller.Endpoints.BaseEndpoint.Deserialize(HttpResponseMessage respo
nse)
at BNetInstaller.Endpoints.Update.UpdateEndpoint.Post()
at BNetInstaller.Program.InstallProduct(Options options, AgentApp app)
at BNetInstaller.Program.Run(Options options)
at BNetInstaller.Program.Main(String[] args)
at BNetInstaller.Program.

(String[] args)

**Comment by n0vares** [comment]
> I'm getting the following error:
> 
> Unhandled Exception: System.ComponentModel.Win32Exception: Only part of a ReadProcessMemory or WriteProcessMemory request was completed
> at System.Diagnostics.NtProcessManager.GetModuleInfos(Int32 processId, Boolean firstModuleOnly)
> at System.Diagnostics.NtProcessManager.GetFirstModuleInfo(Int32 processId)
> at System.Diagnostics.Process.get_MainModule()
> at D2RModding.Program.Main(String[] args)

For me, this only happens if I try to re-open it too quickly after closing it. Make sure you don't have any hanging d2r processes, try rebooting. It'll say that a few times if it crashes and I reopen quickly. Then eventually opens again.

**Comment by shalzuth** [comment]
Latest version should solve this - let me know if there are any issues still.

**Comment by veenhal** [comment]
I'm still getting the following error:

Unhandled Exception: System.ComponentModel.Win32Exception: Only part of a ReadProcessMemory or WriteProcessMemory request was completed
at System.Diagnostics.NtProcessManager.GetModuleInfos(Int32 processId, Boolean firstModuleOnly)
at System.Diagnostics.NtProcessManager.GetFirstModuleInfo(Int32 processId)
at System.Diagnostics.Process.get_MainModule()
at D2RModding.Program.Main(String[] args)

I have updated graph drivers. but I'm using WIN7. I was running: D2RModding.exe as an Admin

**Comment by csuhta** [comment]
D2R requires Windows 10

**Comment by veenhal** [comment]
@csuhta I didn't know that. :( 

Thanks!

I just finished installing win10 :)
